#!/usr/bin/env python3

"""get-filtered-wsl-path - Get $PATH without most Windows path directories."""

import os
import shutil


KEEP_CONTAINING = ('clip.exe', 'code', 'code-insiders')
"""I'll preserve the dirs from the Windows path that give me these commands."""


def get_filtered_path() -> str:
    """Read $PATH, filter out most directories from Windows, and return it."""
    keep_dirs = [os.path.dirname(filename)
                 for filename in map(shutil.which, KEEP_CONTAINING)
                 if filename]

    old_path = os.getenv('PATH')
    if not old_path:
        raise RuntimeError('$PATH environment variable is absent or empty')

    return ':'.join(dirname for dirname in old_path.split(':')
                    if not dirname.startswith('/mnt/') or dirname in keep_dirs)


if __name__ == '__main__':
    print(get_filtered_path())
