#!/usr/bin/env python3

# Copyright (c) 2022, 2023 Eliah Kagan
#
# Permission to use, copy, modify, and/or distribute this software for any
# purpose with or without fee is hereby granted.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES WITH
# REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY
# AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT,
# INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM
# LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR
# OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
# PERFORMANCE OF THIS SOFTWARE.

"""get-filtered-wsl-path - Get $PATH without most Windows path directories."""

import os
import shutil


KEEP_CONTAINING = ('clip.exe', 'code', 'code-insiders')
"""I'll preserve the dirs from the Windows path that give me these commands."""


def get_filtered_path() -> str:
    """Read $PATH, filter out most directories from Windows, and return it."""
    keep_dirs = {os.path.dirname(filename)
                 for command in KEEP_CONTAINING
                 if (filename := shutil.which(command))}

    old_path = os.getenv('PATH')
    if not old_path:
        raise RuntimeError('$PATH environment variable is absent or empty')

    return ':'.join(dirname for dirname in old_path.split(':')
                    if not dirname.startswith('/mnt/') or dirname in keep_dirs)


if __name__ == '__main__':
    print(get_filtered_path())
